main/urls.py
from django.urls import path
from davao_requests import views
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('personnel/', views.list_view_personnel, name='personnel_view'),
    path('save_personnel/', views.save_personnel_data, name='save_personnel'),
    path('delete_personnel/<personnel_id>/', views.delete_personnel, name='delete_personnel'),
    path('edit_personnel/<personnel_id>/', views.edit_personnel_data, name='edit_personnel')
]

requisition_project/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from . import settings
from django.conf.urls.static import static
from main import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('davao/', include('davao_requests.urls')),
    path('surigao/', include('surigao_requests.urls')),
    path('cotabato/', include('cotabato_requests.urls')),
    path('negros/', include('negros_requests.urls')),
    path('bukidnon/', include('bukidnon_requests.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('authentication.urls')),
    path('sys-settings/', include('sys_settings.urls')),
    re_path(r'^.*/$', views.home),
]

# if settings.DEBUG:
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

davao_requests/models.py
from collections.abc import Collection
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from main.models import Personnel
# Create your models here.
class DavaoRequestHeader(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    # id = models.BigAutoField(primary_key=True)
    rs_number = models.CharField(max_length=16, primary_key=True)
    particulars = models.CharField(max_length=100)
    payee = models.CharField(max_length=70, blank=True, null=True)
    project = models.CharField(max_length=150)
    urgent = models.BooleanField()
    note = models.CharField(max_length=165, null=True, blank=True)
    date_requested = models.DateField()
    date_needed = models.DateField()
    last_modified = models.DateField(auto_now_add=True)
    created = models.DateField(auto_now=True)


class DavaoRequestItems(models.Model):
    header = models.ForeignKey(DavaoRequestHeader, on_delete=models.CASCADE)
    item_id = models.CharField(max_length=100, blank=True)
    ignore = models.BooleanField(default=False)
    description = models.CharField(max_length=60)
    quantity = models.DecimalField(decimal_places=2, max_digits=10, blank=True, default=0)
    unit = models.CharField(max_length=20, blank=True)
    unit_cost = models.DecimalField(decimal_places=2, max_digits=10, blank=True, default=0)
    amount = models.DecimalField(max_digits=10, decimal_places=2, default=0)
    served = models.BooleanField(default=False)

    def __str__(self):
        return self.header.rs_number


class AuthorizedPersons(models.Model):
    header = models.ForeignKey(DavaoRequestHeader, on_delete=models.CASCADE)
    personnel = models.ForeignKey(Personnel, on_delete=models.CASCADE, related_name="AuthorizedPersonsDavao", null=True)
    # personnel = models.ManyToManyField(Personnel)
    name = models.CharField(max_length=53, null=True, blank=True)
    title = models.CharField(max_length=30, null=True, blank=True)
    signature = models.ImageField(upload_to='signatures/', blank=True)
    signed = models.BooleanField(null=True, default=False)

    def __str__(self):
        return f"{self.personnel.name} {self.personnel.title}"
    

class Monitoring(models.Model):
    header = models.ForeignKey(DavaoRequestItems, on_delete=models.CASCADE, null=True, blank=True)
    PO_no = models.CharField(max_length=100, null=True, blank=True)
    PO_date = models.DateField(null=True, blank=True)
    delivery_date = models.DateField(null=True, blank=True)
    receiving_report = models.CharField(max_length=100, null=True, blank=True)
    DR_no = models.CharField(max_length=16, null=True, blank=True)
    SI_no = models.CharField(max_length=16, null=True, blank=True)
    OR_no = models.CharField(max_length=16, null=True, blank=True)
    CR_no = models.CharField(max_length=16, null=True, blank=True)
    withdrawal_no = models.CharField(max_length=16, null=True, blank=True)
    item_date = models.DateField(null=True, blank=True)


@receiver(post_save, sender=DavaoRequestItems)
def post_save_trigger(sender, instance, created, **kwargs):
    if created:
        Monitoring.objects.create(header=instance)

main/models.py
from django.db import models

# Create your models here.
class Personnel(models.Model):
    name = models.CharField(max_length=53)
    title = models.CharField(max_length=30)
    signature = models.ImageField(upload_to='signatures/personnel/', blank=True)
    default = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} {self.name}"

main/forms.py
from django import forms
# from .models import DavaoAuthorizedPersons, CotabatoAuthorizedPersons, NegrosAuthorizedPersons, SurigaoAuthorizedPersons
from davao_requests.models import AuthorizedPersons as dvo_authorizedPerson
from cotabato_requests.models import AuthorizedPersons as cbt_authorizedPerson
from negros_requests.models import AuthorizedPersons as ngro_authorizedPerson
from surigao_requests.models import AuthorizedPersons as srgo_authorizedPerson

from .models import Personnel
        
class PersonnelForm(forms.ModelForm):
    TITLE_CHOICES = {
        'RB':'Requested by',
        'PB':'Prepared by',
        'CB':'Checked by',
        'RA':'Recommending Approval',
        'AB':'Approved by'
    }
    class Meta:
        model = Personnel
        fields = [
            'name',
            'title',
            'signature',
            'default'
        ]
        TITLE_CHOICES = {
        'Requested by':'Requested by',
        'Prepared by':'Prepared by',
        'Checked by':'Checked by',
        'Recommending Approval':'Recommending Approval',
        'Approved by':'Approved by'
    }
        
        widgets = {
            'name':forms.TextInput(attrs={'class':'form-control'}),
            'title':forms.Select(attrs={'class':'form-control'}, choices=TITLE_CHOICES),
            'signature':forms.FileInput(attrs={'class':'form-control'})
        }

main/views.py
from django.shortcuts import render, redirect
from django.urls import reverse
from .models import Personnel
from .forms import PersonnelForm
from django.contrib import messages
# Create your views here.
def home(request):
    if request.user.is_authenticated:
        # return render(request, 'main/home.html')
        return redirect(reverse('davao'))
    else:
        return redirect('login')


def add_personnel_view(request):
    pass

def list_view_personnel(request):
    personnel = Personnel.objects.all()
    return render(request, 'main/actions/list_viewPersonnel.html', {'personnel':personnel, 'title':'Select Location'})

def save_personnel_data(request):
    if request.method == 'POST':
       
        form = PersonnelForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Personnel Addedd Successfully')
            
    return redirect(reverse('personnel_view'))

def edit_personnel_data(request, personnel_id):
    if request.method == 'POST':
       
        form = PersonnelForm(request.POST, request.FILES, instance=Personnel.objects.get(pk=personnel_id))
        if form.is_valid():
            form.save()
            messages.success(request, 'Personnel Updated Successfully')
            
    return redirect(reverse('personnel_view'))


def delete_personnel(request, personnel_id):
    personnel = Personnel.objects.get(pk=personnel_id)
    personnel.delete()
    
    return redirect(reverse('personnel_view'))

main/templates/main/actions/dashboard.html
{% extends 'main/base.html' %}
{% load static %}

{% load humanize %}

{% block content-title %}{{title|upper}} MONITORING{% endblock %}

{% block content %}
{% load maintags %}


<style>
    #monitoring-table {
        width: 1500px;
        font-size: 10px;
    }

    .particulars_col,
    .description_col,
    .receiving_report_col {
        width: 600px;
    }

    .withdrawal_no_col {
        width: 200px;
    }
    .rs_no_col,
    .rs_date_col,
    .po_date_col,
    .date_col,
    .or_on_col,
    .si_no_col,
    .cr_no_col {
        width: 100px;
    }

    .delivery_date_col {
        width: 150px;
    }
    .supplier_col {
        width: 800px;
    }

    .scrollable {
        /* width: 130%;
    height: 1020px; */
    height: 80vh;
        overflow: scroll;
        /* background-color: gray; */
    }
</style>
<div class="scrollable" style="width: 100%;">
    <div class="row p-0 m-0">
        <p>Show/Hide Columns</p>
        <div class="col">
            <input type="checkbox" name="rs-label" id="rs_no_col">
            <label for="rs-label">R.S. NO</label>
        </div>

        <div class="col">
            <input type="checkbox" name="rs-date-label" id="rs_date_col">
            <label for="rs-date-label">R.S. Date</label>
        </div>

        <div class="col">
            <input type="checkbox" name="po-date-label" id="po_date_col">
            <label for="po-date-label">P.O. Date</label>
        </div>

        <div class="col">
            <input type="checkbox" name="dr-label" id="dr_no_col">
            <label for="dr-label">DR</label>
        </div>

        <div class="col">
            <input type="checkbox" name="supplier-label" id="supplier_col">
            <label for="supplier-label">Supplier</label>
        </div>

        <div class="col">
            <input type="checkbox" name="description-label" id="description_col">
            <label for="description-label">Description</label>
        </div>

        <div class="col">
            <input type="checkbox" name="particulars-label" id="particulars_col">
            <label for="particulars-label">Particulars</label>
        </div>

        <div class="col">
            <input type="checkbox" name="unit-label" id="unit_col">
            <label for="unit-label">Unit</label>
        </div>

        <hr>
    </div>
    <table id="monitoring-table" class="table table-lg text-center table-striped table-hover" style="font-size: 7pt;">
        <thead>
            <th class="rs_no_col align-middle" style="display: none;">RS NO.</th>
            <th class="rs_date_col align-middle" style="display: none;">RS DATE</th>
            <th class="po_no_col align-middle">PO NO.</th>
            <th class="po_date_col align-middle" style="display: none;">PO DATE</th>
            <th class="project_id_col align-middle">Project I.D.</th>
            <th class="supplier_col align-middle align-middle" style="display: none;">SUPPLIER</th>
            <th class="description_col align-middle" style="display: none;">DESCRIPTION</th>
            <th class="po_qty_col align-middle">PO QTY</th>
            <th class="unit_col align-middle" style="display: none;">UNIT</th>
            <th class="unit_price_col align-middle">UNIT PRICE</th>
            <th class="total_amount_col align-middle">TOTAL AMOUNT</th>
            <th class="particulars_col align-middle" style="display: none;">PARTICULARS<br>REMARKS</th>
            <th class="delivery_date_col align-middle">DELIVERY DATE</th>
            <th class="receiving_report_col align-middle">RECEIVING REPORT</th>
            <th class="dr_no_col align-middle" style="display: none;">D.R. NO.</th>
            <th class="si_no_col align-middle">S.I. NO.</th>
            <th class="or_on_col align-middle">O.R. NO.</th>
            <th class="cr_no_col align-middle">C.R. NO.</th>
            <th class="withdrawal_no_col align-middle">WITHDRAWAL NO.</th>
            <th class="date_col align-middle">DATE</th>
            <th class="reference_col align-middle">REFERENCE</th>
            <th class="served_col align-middle">SERVED<br>UNSERVED</th>
        </thead>
        <tbody>
            {% for d in data %}
            {% if not d.header.ignore %}
            <tr role="button" data-bs-toggle="modal" data-bs-target="#monitoring-update-form{{d.id}}">
                <td class="rs_no_col align-middle" style="display: none;">{{d.header.header.rs_number}}</td>
                <td class="rs_date_col align-middle" style="display: none;">{{d.header.header.date_requested}}</td>
                <td class="po_no_col align-middle">{{d.PO_no|clean_empty}}</td>
                <td class="po_date_col align-middle" style="display: none;">{{d.PO_date|clean_empty}}</td>
                <td class="project_id_col align-middle">
                    {{d.header.item_id|clean_empty}}
                </td>
                <td class="supplier_col align-middle" style="display: none;">{{d.header.header.payee}}</td>
                <td class="description_col align-middle" style="display: none;">{{d.header.description}}</td>
                <td class="po_qty_col align-middle">{{d.header.quantity}}</td>
                <td class="unit_col align-middle" style="display: none;">{{d.header.unit}}</td>
                <td class="unit_price_col align-middle">{{d.header.unit_cost|intcomma}}</td>
                <td class="total_amount_col align-middle">₱{{d.header.amount|intcomma}}</td>
                <td class="particulars_col align-middle" style="display: none;">{{d.header.header.particulars}}</td>
                <td class="delivery_date_col align-middle">
                    <span>
                        {{d.delivery_date|clean_empty}}
                    </span>
                </td>
                <td class="receiving_report_col align-middle">{{d.receiving_report|clean_empty}}</td>
                <td class="dr_no_col align-middle" style="display: none;">{{d.DR_no|clean_empty}}</td>
                <td class="si_no_col align-middle">{{d.SI_no|clean_empty}}</td>
                <td class="or_on_col align-middle">{{d.OR_no|clean_empty}}</td>
                <td class="cr_no_col align-middle">{{d.CR_no|clean_empty}}</td>
                <td class="withdrawal_no_col align-middle">{{d.withdrawal_no|clean_empty}}</td>
                <td class="date_col align-middle">{{d.item_date|clean_empty}}</td>
                <td class="reference_col align-middle">{{d.reference|clean_empty}}</td>
                <td class="served_col align-middle">
                    {% if d.header.served %}
                    <i class="bi bi-check-circle-fill text-success">
                        <p style="display: none;">a</p>
                    </i>
                    {% else %}
                    <i class="bi bi-x-circle-fill text-danger">
                        <p style="display: none;">b</p>
                    </i>
                    {% endif %}
                </td>
            </tr>
            {% endif %}
            <!-- Modal -->
            <div class="modal fade" id="monitoring-update-form{{d.id}}" tabindex="-1"
                aria-labelledby="exampleModalLabel" aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">

                        {% csrf_token %}
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">
                                {% if d.header.item_id %}
                                Project ID: {{d.header.item_id}}
                                {% else %}
                                R.S. Number: {{d.header.header.rs_number}}
                                {% endif %}
                            </h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        <form method="post" action="/{{title|lower}}/monitoringForm/">
                            <div class="modal-body" id="monitoring-modal">

                                {% if title == 'Davao' %}
                                {% load davao_tags %}
                                {% monitoringModalForm d.id %}

                                {% elif title == 'Cotabato' %}
                                {% load cotabato_tags %}
                                {% monitoringModalForm d.id %}
                                
                                {% elif title == 'Negros' %}
                                {% load negros_tags %}
                                {% monitoringModalForm d.id %}

                                {% elif title == 'Surigao' %}
                                {% load surigao_tags %}
                                {% monitoringModalForm d.id %}

                                {% elif title == 'Bukidnon' %}
                                {% load bukidnon_tags %}
                                {% monitoringModalForm d.id %}

                                {% endif %}

                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-dark">Save changes</button>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
            {% endfor %}
        </tbody>
    </table>
</div>


<script>
    $(document).on('submit', '#monitoringForm', function (e) {
        e.preventDefault();
    });

    let classes = [
        "rs_no_col", "rs_date_col", "po_no_col", "po_date_col",
        "project_id_col", "supplier_col", "description_col", "po_qty_col",
        "unit_col", "unit_price_col", "total_amount_col", "particulars_col",
        "delivery_date_col", "receiving_report_col", "dr_no_col", "si_no_col",
        "or_on_col", "cr_no_col", "withdrawal_no_col", "date_col", "reference_col",
        "served_col"
    ]

    for (let i = 0; i < classes.length; i++) {
        $(function () {
            $("#" + classes[i]).change(function () {
                var isChecked = $(this).is(':checked');
                if (isChecked) {
                    $('.' + classes[i]).show();
                } else {
                    $('.' + classes[i]).hide();
                }

            });
        });
    }

</script>


<script type="text/javascript">
    $(function () {
        $('.table').DataTable();
        $('#id_urgent').change(function () {
            var checked = $(this).is(':checked');
            if (checked) {
                // alert('Checked')
            } else {
                // alert('Unchecked')
            }
        })
    });
</script>

{% endblock %}

main/templates/main/actions/list_view_items.html
{% extends 'main/base.html' %}
{% load humanize %}
{% block content-title %} {{title}} Items {% endblock %}
{% block content %}



<div class="table-responsive small rounded shadow p-3 mb-3">
    <table class="table table-striped table-sm table-hover" id="items-data-table" style="font-size: 9pt;">
        <thead>
            <tr>
                <th>RS Number</th>
                <th>Description</th>
                <th>Unit</th>
                <th class="text-center">Unit Cost</th>
                <th class="text-center">Amount</th>
                <th>Served</th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            {% comment %} {% if not item.ignore %} {% endcomment %}

            <tr>
                <td>
                    {% if title == 'Davao' %}
                    <a href="{% url 'davao_rsView' item.header.rs_number %}" class="text-decoration-none text-none">
                        {{item.header.rs_number}}
                    </a>
                    {% elif title == 'Cotabato' %}
                    <a href="{% url 'cotabato_rsView' item.header.rs_number %}" class="text-decoration-none text-none">
                        {{item.header.rs_number}}
                    </a>
                    {% elif title == 'Negros' %}
                    <a href="{% url 'negros_rsView' item.header.rs_number %}" class="text-decoration-none text-none">
                        {{item.header.rs_number}}
                    </a>
                    {% elif title == 'Surigao' %}
                    <a href="{% url 'surigao_rsView' item.header.rs_number %}" class="text-decoration-none text-none">
                        {{item.header.rs_number}}
                    </a>
                    {% elif title == 'Bukidnon' %}
                    <a href="{% url 'bukidnon_rsView' item.header.rs_number %}" class="text-decoration-none text-none">
                        {{item.header.rs_number}}
                    </a>
                    {% endif %}
                </td>
                <td>{{item.description}} {{item.item_id}}</td>
                <td>{{item.unit}}</td>
                <td class="text-center">{{item.unit_cost|intcomma}}</td>
                <td class="text-center">₱{{item.amount|intcomma}}</td>
                <td class="text-center">
                    {% if item.served %}
                    Served
                    {% else %}
                    Unserved
                    {% endif %}
                </td>
                <td class="text-end">
                    <button data-bs-toggle="modal" data-bs-target="#editItemModal-{{item.id}}"
                        class="btn btn-outline-dark btn-sm">
                        <i class="bi bi-pencil-fill"></i>
                        <span class="visually-hidden">Button</span>
                        Edit
                    </button>
                    <button onclick="confirmDelete('{{ item.id }}', '{{ item.description }}' + ' {{ item.item_id }}')"
                        role="button" class="btn btn-outline-danger btn-sm">
                        <i class="bi bi-trash3-fill"></i>
                        <span class="visually-hidden">Button</span>
                        Delete
                    </button>

                    {% if title == 'Davao' %}
                    <script>
                        function confirmDelete(item_id, info) {
                            if (confirm("Are you sure you want to delete request item " + info + "?")) {
                                window.location.href = "{% url 'davao_delete_item' item.id %}";
                            } else {
                                // Do nothing or provide feedback to the user that the delete action was canceled.
                            }
                        }
                    </script>
                    {% elif title == 'Cotabato' %}
                    <script>
                        function confirmDelete(item_id, info) {
                            if (confirm("Are you sure you want to delete request item " + info + "?")) {
                                window.location.href = "{% url 'cotabato_delete_item' item.id %}";
                            } else {
                                // Do nothing or provide feedback to the user that the delete action was canceled.
                            }
                        }
                    </script>
                    {% elif title == 'Negros' %}
                    <script>
                        function confirmDelete(item_id, info) {
                            if (confirm("Are you sure you want to delete request item " + info + "?")) {
                                window.location.href = "{% url 'negros_delete_item' item.id %}";
                            } else {
                                // Do nothing or provide feedback to the user that the delete action was canceled.
                            }
                        }
                    </script>
                    {% elif title == 'Surigao' %}
                    <script>
                        function confirmDelete(item_id, info) {
                            if (confirm("Are you sure you want to delete request item " + info + "?")) {
                                window.location.href = "{% url 'surigao_delete_item' item.id %}";
                            } else {
                                // Do nothing or provide feedback to the user that the delete action was canceled.
                            }
                        }
                    </script>
                    {% elif title == 'Bukidnon' %}
                    <script>
                        function confirmDelete(item_id, info) {
                            if (confirm("Are you sure you want to delete request item " + info + "?")) {
                                window.location.href = "{% url 'bukidnon_delete_item' item.id %}";
                            } else {
                                // Do nothing or provide feedback to the user that the delete action was canceled.
                            }
                        }
                    </script>
                    {% endif %}
                </td>
            </tr>
            <!-- Modal -->
            <div class="modal fade" id="editItemModal-{{item.id}}" tabindex="-1" aria-labelledby="exampleModalLabel"
                aria-hidden="true">
                <div class="modal-dialog">
                    <div class="modal-content">
                        <div class="modal-header">
                            <h1 class="modal-title fs-5" id="exampleModalLabel">Update Item</h1>
                            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                        </div>
                        {% if title == 'Davao' %}
                        <form action="{% url 'davao_edit_item_view' item.id %}" method="post">
                            <div class="modal-body calculation-form">
                                {% load davao_tags %}
                                {% csrf_token %}
                                {% editItemsModal item.id %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-dark">Save changes</button>
                            </div>
                        </form>
                        {% elif title == 'Cotabato' %}
                        <form action="{% url 'cotabato_edit_item_view' item.id %}" method="post">
                            <div class="modal-body calculation-form">
                                {% load cotabato_tags %}
                                {% csrf_token %}
                                {% editItemsModal item.id %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-dark">Save changes</button>
                            </div>
                        </form>
                        {% elif title == 'Negros' %}
                        <form action="{% url 'negros_edit_item_view' item.id %}" method="post">
                            <div class="modal-body calculation-form">
                                {% load negros_tags %}
                                {% csrf_token %}
                                {% editItemsModal item.id %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-dark">Save changes</button>
                            </div>
                        </form>
                        {% elif title == 'Surigao' %}
                        <form action="{% url 'surigao_edit_item_view' item.id %}" method="post">
                            <div class="modal-body calculation-form">
                                {% load surigao_tags %}
                                {% csrf_token %}
                                {% editItemsModal item.id %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-dark">Save changes</button>
                            </div>
                        </form>
                        {% elif title == 'Bukidnon' %}
                        <form action="{% url 'bukidnon_edit_item_view' item.id %}" method="post">
                            <div class="modal-body calculation-form">
                                {% load bukidnon_tags %}
                                {% csrf_token %}
                                {% editItemsModal item.id %}
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                                <button type="submit" class="btn btn-dark">Save changes</button>
                            </div>
                        </form>
                        {% endif %}
                    </div>
                </div>
            </div>
            {% comment %} {% endif %} {% endcomment %}
            {% endfor %}
        </tbody>
    </table>
</div>

<script>
    $(document).ready(function () {
        $('#items-data-table').DataTable();
    });
    var active = document.getElementById('items-nav');
    var current = document.getElementById('side-navbar');
    var current = current.getElementsByClassName('active');
    current[0].className = current[0].className.replace("active", "");
    active.className += " active";

    $(document).ready(function () {
        // Event handlers for 'input' events on #qty and #unit_cost
        $('#id_quantity, #id_unit_cost').on('input', function () {
            var qtyValue = parseFloat($('#id_quantity').val()) || 0;
            var unitCostValue = parseInt($('#id_unit_cost').val()) || 0;

            var rs = qtyValue * unitCostValue;
            $('#id_amount').val(rs);
        });
    });
</script>

{% endblock %}